#!/bin/sh
# Writes the served installer: the install source with its Paperland block replaced by
# the built Paperland install and uninstall (paperland/build.sh output), each verbatim
# as the body of a function that runs in a subshell.
# Usage: scripts/assemble-install.sh INSTALL_SOURCE PAPERLAND_BUILD_DIR OUT_FILE
set -eu

die() { printf 'assemble-install: %s\n' "$*" >&2; exit 1; }

[ $# -eq 3 ] || die "usage: assemble-install.sh INSTALL_SOURCE PAPERLAND_BUILD_DIR OUT_FILE"
src=$1 built=$2 out=$3
for file in "$src" "$built/install" "$built/uninstall"; do [ -f "$file" ] || die "missing $file"; done
[ "$(grep -c '^# BEGIN PAPERLAND' "$src")" = 1 ] && [ "$(grep -c '^# END PAPERLAND$' "$src")" = 1 ] ||
  die "$src needs exactly one '# BEGIN PAPERLAND' ... '# END PAPERLAND' block"

awk -v install="$built/install" -v uninstall="$built/uninstall" '
  /^# BEGIN PAPERLAND/ {
    print "# BEGIN PAPERLAND: generated by scripts/build-site.sh from paperland/install and"
    print "# paperland/uninstall with paperland/release.env inlined; edit those, not this."
    print "# Each runs in its own subshell, so its functions, variables, set -eu, traps and"
    print "# exits stay inside it, exactly as when it ran as a script of its own."
    print "paperland_install() ("
    while ((getline line < install) > 0) print line
    print ")"
    print "paperland_uninstall() ("
    while ((getline line < uninstall) > 0) print line
    print ")"
    skip = 1
    next
  }
  /^# END PAPERLAND$/ { skip = 0 }
  !skip { print }
' "$src" > "$out.tmp"
sh -n "$out.tmp" || { rm -f "$out.tmp"; die "the assembled installer has a syntax error"; }
mv "$out.tmp" "$out"
