#!/bin/sh
# Packages a Paperland git ref as the new tip of the plugin repo's `release` branch
# and pins that commit in release.env.
#
# Usage: publish-plugin-release.sh [--push] PAPERLAND_GIT_REF
#
# Without --push the release commit stays in a kept work directory (printed) and
# nothing leaves this machine; push it from there, or rerun with --push.
# Overrides: PAPERLAND_SOURCE_URL (Paperland source repo), PLUGIN_REPO (release
# repo; defaults to PLUGIN_URL from release.env), RELEASE_ENV (file to update),
# PUBLISH_UNVALIDATED=1 (allow publishing without omarchy-plugin-validate).
# Publish from an Omarchy machine (hotrod) so the package is validated.
set -eu

die() { printf 'publish: %s\n' "$*" >&2; exit 1; }

root=$(cd "$(dirname "$0")" && pwd)
SOURCE_URL=${PAPERLAND_SOURCE_URL:-https://github.com/jsonMartin/paperland.git}
RELEASE_ENV=${RELEASE_ENV:-$root/release.env}

push=
if [ "${1:-}" = --push ]; then push=1; shift; fi
[ $# -eq 1 ] && [ -n "$1" ] || die "usage: publish-plugin-release.sh [--push] PAPERLAND_GIT_REF"
ref=$1

plugin_url=$(sed -n 's/^PLUGIN_URL=//p' "$RELEASE_ENV")
PLUGIN_REPO=${PLUGIN_REPO:-$plugin_url}
[ -n "$PLUGIN_REPO" ] || die "no PLUGIN_URL in $RELEASE_ENV"
export GIT_TERMINAL_PROMPT=0

tmp=$(mktemp -d "${TMPDIR:-/tmp}/paperland-release.XXXXXX")
trap 'rm -rf "$tmp/src" "$tmp/pkg"; if [ -n "$push" ]; then rm -rf "$tmp"; fi' EXIT

git clone --quiet --no-checkout -- "$SOURCE_URL" "$tmp/src"
source_sha=$(git -C "$tmp/src" rev-parse --verify --quiet "$ref^{commit}" ||
  git -C "$tmp/src" rev-parse --verify --quiet "origin/$ref^{commit}") || die "unknown Paperland ref: $ref"
git -C "$tmp/src" checkout --quiet --detach "$source_sha"
"$tmp/src/package-omarchy" "$tmp/pkg"
if command -v omarchy-plugin-validate >/dev/null 2>&1; then
  omarchy-plugin-validate "$tmp/pkg"
elif [ "${PUBLISH_UNVALIDATED:-}" = 1 ]; then
  echo "publish: omarchy-plugin-validate not found; publishing UNVALIDATED (PUBLISH_UNVALIDATED=1)" >&2
else
  die "omarchy-plugin-validate not found; publish from an Omarchy machine, or set PUBLISH_UNVALIDATED=1"
fi

rel=$tmp/release
git init --quiet "$rel"
git -C "$rel" remote add origin "$PLUGIN_REPO"
remote_status=0
git -C "$rel" ls-remote --exit-code origin refs/heads/release >/dev/null || remote_status=$?
case "$remote_status" in
  0) git -C "$rel" fetch --quiet origin release
     git -C "$rel" checkout --quiet -B release FETCH_HEAD
     git -C "$rel" rm -r --quiet -- . ;;
  2) git -C "$rel" checkout --quiet --orphan release ;;
  *) die "cannot reach $PLUGIN_REPO (git ls-remote exit $remote_status); create the repo first" ;;
esac
cp -R "$tmp/pkg/." "$rel/"
git -C "$rel" add -A
git -C "$rel" diff --cached --quiet && die "package for $source_sha is identical to the current release"
git -C "$rel" commit --quiet -m "release: Paperland $source_sha" -m "Generated by getpaper.sh scripts/publish-plugin-release.sh from $SOURCE_URL at $ref."
new_sha=$(git -C "$rel" rev-parse HEAD)

if [ -n "$push" ]; then
  # Before pinning: a failed push must not leave release.env naming a commit nobody can fetch.
  git -C "$rel" push --quiet origin release
  echo "Pushed release to $PLUGIN_REPO"
  # Installers clone the release branch explicitly, but Omarchy's own tools follow
  # the default branch; GitHub makes the first branch pushed to an empty repo the default.
  git -C "$rel" ls-remote --symref origin HEAD | grep -q '^ref: refs/heads/release[[:space:]]' ||
    die "the default branch of $PLUGIN_REPO is not release; set it on GitHub, then rerun. release.env was not changed."
fi
sed "s/^PLUGIN_SHA=.*/PLUGIN_SHA=$new_sha/" "$RELEASE_ENV" > "$RELEASE_ENV.tmp"
mv "$RELEASE_ENV.tmp" "$RELEASE_ENV"

echo "Release commit: $new_sha (Paperland $source_sha)"
echo "Updated $RELEASE_ENV; commit it, then rebuild with build.sh."
[ -n "$push" ] || echo "Not pushed. To publish: git -C $rel push origin release"
